<a href="https://colab.research.google.com/github/mohammedovich/ML/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
 dataset = pd.read_csv('Data.csv')
 # : - is a range between columns to select
 # automatically, take all columns except the last column
 # [:, :-1] - the first ':' is the lower band i.e. starting at 0, ':-1' is the
 # higher band except the last column
 x = dataset.iloc[:, :-1].values

# [:, -1] note that we removed the range ':' from second param, as it will select
# select the last column ONLY
 y = dataset.iloc[:, -1].values
 

In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [6]:
# in  a situation where you have a large dataset, and you have 1% of missing data
# you can just delete the data as it will have no impact on the model being trained
# and no loss of accuracy.
# to handle missing data, use sklearn - impute
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# selecting numeric values to be replaced
imputer.fit(x[:, 1:3])

# transform and update the columns those data been updated
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [7]:
# So the transform will updated the missing columns with the overall average of
# of i.e. age and salary. 
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [10]:
# here we want to compute the dataset i.e. the country column has to be transformed
# to numeric representation, i.e.
# France = 1.0 0.0 0.0
# Spain = 0.0 0.0 1.0
# Germany = 0.0 1.0 0.0
# We converting these to numeric to simplify the model learning
#------------------------------
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# we have to cast to an array (ndarray) 
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [12]:
# We are transforming the last column of Purchased, the type is boolean which 
# will be converted to 0 and 1.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [15]:
print(x_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [16]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [17]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [18]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
# Feature Scaling is always done after 'Splitting the dataset into two seperate sets' 
# [WHAT] Featrure scaling: consists of scaling all your variables or your features
# actually to make sure they all take values in the same scale
# [WHY]: Tht the test set is supposed to be a brand new set on which you are going to evaluate your machine learning mode.
# What this means, is that the test set is something you're not supposed to work with for the training and features.
